package com.bank.model;
// Generated Jun 28, 2017 12:51:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer id;
     private double balance;
     private String accountNumber;
     private Date openedDate;
     private int accountStatus;
     private int accountTypeId;
     private Set transactions = new HashSet(0);
     private Set users = new HashSet(0);

    public Account() {
    }

	
    public Account(double balance, String accountNumber, Date openedDate, int accountStatus, int accountTypeId) {
        this.balance = balance;
        this.accountNumber = accountNumber;
        this.openedDate = openedDate;
        this.accountStatus = accountStatus;
        this.accountTypeId = accountTypeId;
    }
    public Account(double balance, String accountNumber, Date openedDate, int accountStatus, int accountTypeId, Set transactions, Set users) {
       this.balance = balance;
       this.accountNumber = accountNumber;
       this.openedDate = openedDate;
       this.accountStatus = accountStatus;
       this.accountTypeId = accountTypeId;
       this.transactions = transactions;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public double getBalance() {
        return this.balance;
    }
    
    public void setBalance(double balance) {
        this.balance = balance;
    }
    public String getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }
    public Date getOpenedDate() {
        return this.openedDate;
    }
    
    public void setOpenedDate(Date openedDate) {
        this.openedDate = openedDate;
    }
    public int getAccountStatus() {
        return this.accountStatus;
    }
    
    public void setAccountStatus(int accountStatus) {
        this.accountStatus = accountStatus;
    }
    public int getAccountTypeId() {
        return this.accountTypeId;
    }
    
    public void setAccountTypeId(int accountTypeId) {
        this.accountTypeId = accountTypeId;
    }
    public Set getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set transactions) {
        this.transactions = transactions;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


