package com.bank.model;
// Generated Jun 28, 2017 12:51:24 PM by Hibernate Tools 4.3.1



/**
 * AccountType generated by hbm2java
 */
public class AccountType  implements java.io.Serializable {


     private Integer id;
     private String accountType;

    public AccountType() {
    }

    public AccountType(String accountType) {
       this.accountType = accountType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }




}


