package com.bank.model;
// Generated Jun 28, 2017 11:29:53 AM by Hibernate Tools 4.3.1



/**
 * Credential generated by hbm2java
 */
public class Credential  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String loginId;
     private String password;

    public Credential() {
    }

    public Credential(User user, String loginId, String password) {
       this.user = user;
       this.loginId = loginId;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


