package com.bank.model;
// Generated Jun 28, 2017 12:51:24 PM by Hibernate Tools 4.3.1



/**
 * TransactionType generated by hbm2java
 */
public class TransactionType  implements java.io.Serializable {


     private Integer id;
     private String transactionType;

    public TransactionType() {
    }

    public TransactionType(String transactionType) {
       this.transactionType = transactionType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }




}


