package com.bank.model;
// Generated Jun 28, 2017 11:29:53 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private Integer id;
     private Account account;
     private String description;
     private Double amount;
     private Date date;
     private Double availableBalance;
     private int transactionStatusId;
     private int transactionTypeId;

    public Transaction() {
    }

	
    public Transaction(Account account, String description, int transactionStatusId, int transactionTypeId) {
        this.account = account;
        this.description = description;
        this.transactionStatusId = transactionStatusId;
        this.transactionTypeId = transactionTypeId;
    }
    public Transaction(Account account, String description, Double amount, Date date, Double availableBalance, int transactionStatusId, int transactionTypeId) {
       this.account = account;
       this.description = description;
       this.amount = amount;
       this.date = date;
       this.availableBalance = availableBalance;
       this.transactionStatusId = transactionStatusId;
       this.transactionTypeId = transactionTypeId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getAvailableBalance() {
        return this.availableBalance;
    }
    
    public void setAvailableBalance(Double availableBalance) {
        this.availableBalance = availableBalance;
    }
    public int getTransactionStatusId() {
        return this.transactionStatusId;
    }
    
    public void setTransactionStatusId(int transactionStatusId) {
        this.transactionStatusId = transactionStatusId;
    }
    public int getTransactionTypeId() {
        return this.transactionTypeId;
    }
    
    public void setTransactionTypeId(int transactionTypeId) {
        this.transactionTypeId = transactionTypeId;
    }




}


