-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 09:55:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `idAddress` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  PRIMARY KEY (`idAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `is_admin` TINYINT NOT NULL DEFAULT 0,
  `Address_idAddress` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_User_Address1_idx` (`Address_idAddress` ASC),
  CONSTRAINT `fk_User_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `mydb`.`Address` (`idAddress`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Credential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Credential` (
  `idCredential` INT NOT NULL AUTO_INCREMENT,
  `loginId` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idCredential`),
  UNIQUE INDEX `loginId_UNIQUE` (`loginId` ASC),
  INDEX `fk_Credential_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Credential_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account Type` (
  `idAccount_Type` INT NOT NULL,
  `account_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAccount_Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `idAccount` INT NOT NULL AUTO_INCREMENT,
  `account_type` VARCHAR(45) NULL,
  `balance` DOUBLE NULL,
  `account_number` VARCHAR(45) NULL,
  `opened_date` DATE NOT NULL,
  `account_status` INT NOT NULL DEFAULT 0,
  `Account Type_idAccount Type` INT NOT NULL,
  PRIMARY KEY (`idAccount`),
  UNIQUE INDEX `idAccount_UNIQUE` (`idAccount` ASC),
  INDEX `fk_Account_Account Type1_idx` (`Account Type_idAccount Type` ASC),
  CONSTRAINT `fk_Account_Account Type1`
    FOREIGN KEY (`Account Type_idAccount Type`)
    REFERENCES `mydb`.`Account Type` (`idAccount_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransactionType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TransactionType` (
  `idTransactionType` INT NOT NULL,
  `transaction_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTransactionType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransactionStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TransactionStatus` (
  `idTransactionStatus` INT NOT NULL,
  `TransactionStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTransactionStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `idTransaction` INT NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `amount` DOUBLE NULL,
  `date` DATE NULL,
  `available_balance` DOUBLE NULL,
  `Account_idAccount` INT NOT NULL,
  `TransactionType_idTransactionType` INT NOT NULL,
  `TransactionStatus_idTransactionStatus` INT NOT NULL,
  PRIMARY KEY (`idTransaction`),
  UNIQUE INDEX `idTransaction_UNIQUE` (`idTransaction` ASC),
  INDEX `fk_Transaction_Account1_idx` (`Account_idAccount` ASC),
  INDEX `fk_Transaction_TransactionType1_idx` (`TransactionType_idTransactionType` ASC),
  INDEX `fk_Transaction_TransactionStatus1_idx` (`TransactionStatus_idTransactionStatus` ASC),
  CONSTRAINT `fk_Transaction_Account1`
    FOREIGN KEY (`Account_idAccount`)
    REFERENCES `mydb`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_TransactionType1`
    FOREIGN KEY (`TransactionType_idTransactionType`)
    REFERENCES `mydb`.`TransactionType` (`idTransactionType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_TransactionStatus1`
    FOREIGN KEY (`TransactionStatus_idTransactionStatus`)
    REFERENCES `mydb`.`TransactionStatus` (`idTransactionStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_has_Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_has_Account` (
  `id` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Account_idAccount` INT NOT NULL,
  INDEX `fk_User_has_Account_Account1_idx` (`Account_idAccount` ASC),
  INDEX `fk_User_has_Account_User1_idx` (`User_idUser` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_User_has_Account_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Account_Account1`
    FOREIGN KEY (`Account_idAccount`)
    REFERENCES `mydb`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
