-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 12:39:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OnlineBanking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnlineBanking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineBanking` DEFAULT CHARACTER SET utf8 ;
USE `OnlineBanking` ;

-- -----------------------------------------------------
-- Table `OnlineBanking`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `zip_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBanking`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `is_admin` TINYINT NOT NULL DEFAULT 0,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUser_UNIQUE` (`id` ASC),
  INDEX `fk_user_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_user_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `OnlineBanking`.`address` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBanking`.`credential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`credential` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `loginId` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `loginId_UNIQUE` (`loginId` ASC),
  INDEX `fk_credential_user_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_credential_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineBanking`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBanking`.`accountType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`accountType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBanking`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `balance` DOUBLE NOT NULL DEFAULT 0.0,
  `account_number` VARCHAR(45) NOT NULL,
  `opened_date` DATE NOT NULL,
  `account_status` INT NOT NULL DEFAULT 0,
  `accountType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idAccount_UNIQUE` (`id` ASC),
  INDEX `fk_account_accountType1_idx` (`accountType_id` ASC),
  UNIQUE INDEX `account_number_UNIQUE` (`account_number` ASC),
  CONSTRAINT `fk_account_accountType1`
    FOREIGN KEY (`accountType_id`)
    REFERENCES `OnlineBanking`.`accountType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBanking`.`transactionStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`transactionStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `TransactionStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBanking`.`transactionType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`transactionType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transaction_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBanking`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(250) NOT NULL,
  `amount` DOUBLE NULL,
  `date` DATE NULL,
  `available_balance` DOUBLE NULL,
  `transactionStatus_id` INT NOT NULL,
  `transactionType_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTransaction_UNIQUE` (`id` ASC),
  INDEX `fk_transaction_transactionStatus1_idx` (`transactionStatus_id` ASC),
  INDEX `fk_transaction_transactionType1_idx` (`transactionType_id` ASC),
  INDEX `fk_transaction_account1_idx` (`account_id` ASC),
  CONSTRAINT `fk_transaction_transactionStatus1`
    FOREIGN KEY (`transactionStatus_id`)
    REFERENCES `OnlineBanking`.`transactionStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaction_transactionType1`
    FOREIGN KEY (`transactionType_id`)
    REFERENCES `OnlineBanking`.`transactionType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaction_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `OnlineBanking`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBanking`.`user_has_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`user_has_account` (
  `user_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `account_id`),
  INDEX `fk_user_has_account_account1_idx` (`account_id` ASC),
  INDEX `fk_user_has_account_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_account_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `OnlineBanking`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_account_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `OnlineBanking`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
