-- MySQL Script generated by MySQL Workbench
-- Tue Jun 27 16:01:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OnlineBanking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnlineBanking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineBanking` DEFAULT CHARACTER SET utf8 ;
USE `OnlineBanking` ;

-- -----------------------------------------------------
-- Table `OnlineBanking`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`user` (
  `id_user` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `second_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBanking`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBanking`.`account` (
  `id_account` INT NOT NULL,
  `account_number` VARCHAR(45) NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_account`),
  INDEX `fk_account_user_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_account_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `OnlineBanking`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
